# Generated by Django 4.1 on 2022-08-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, verbose_name='회사이름')),
            ],
        ),
        migrations.CreateModel(
            name='Recruitments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='국가')),
                ('region', models.CharField(max_length=15, verbose_name='지역')),
                ('position', models.CharField(max_length=30, verbose_name='채용포지션')),
                ('recruit_compensation', models.IntegerField(verbose_name='채용보상금')),
                ('contents', models.TextField(verbose_name='채용내용')),
                ('skill', models.CharField(max_length=30, verbose_name='기술')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='회사명')),
            ],
        ),
    ]
